### ISSUE TITLE
finish docs, cleanup, finalize

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-react-adapter#21]
Make sure that this adapter has everything required for LaxarJS v2:

 - [x] widget area support
 - [x] working spec tests
 - [x] up-to-date docs

**Comment by jonaswjs** [comment]
The hint about the Documentation will not only be visible at the GitHub site but also on the npm package information site. We should use a different phrase.

```html
<span class="laxar-developer-view">This is the developer version. Take a look at our <a href="http://www.laxarjs.org/docs/laxar-react-adapter">documentation site</a> with the released version.</span>
```

And fix the link: `http://www.laxarjs.org/docs/laxar-react-adapter` should be `http://www.laxarjs.org/docs/laxar-react-adapter-latest`

**Comment by x1B** [comment]
Good points!

**Comment by x1B** [comment]
I recommend the following text:

```html
<span class="laxar-developer-view">
   Take a look at the <a href="http://www.laxarjs.org/docs/laxar-react-adapter-latest">documentation site</a> to browse documentation for all releases of this artifact.
</span>
```

**Comment by alex3683** [comment]
Cool thing, but I don't quite understand the meaning of `laxar-developer-view`. From what I understand that the class does, something like `laxar-external-documentation-hint` would be more suitable.

**Comment by x1B** [comment]
@alex3683 @jonaswjs agreed, the class name `laxar-external-documentation-hint` makes more sense.

**Comment by alex3683** [comment]
@x1B Two more things:
- [x] use ES2015 class syntax instead of `React.createClass()` (there is already a deprecation warning from React)
- [x] In the controls part, a description on how to *use* the control within a widget is missing

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

The `"react"` integration technology was simplified in an incompatible manner for LaxarJS v2.
The following things were modified:

 - the widget's `create` export is now expected to return just a render function,
 - the `axReactRender` method no longer takes arguments,
 - the `AxWidgetArea` was changed: the `areaName` prop was renamed to `name`. The `axVisibility` prop is only required if the `visible` prop (now `true` by default) is also used.

For numerous examples, refer to the [README.md](https://github.com/LaxarJS/laxar-react-adapter/blob/c241361/README.md#usage).

**Comment by jpommerening** [comment]
Short recipe on how to quickly adapt to the breaking change:

- change the create function to return the `render` function instead of `{ onDomAvailable }`
- change the render function to return React elements instead of passing them to `reactRender()`
- replace calls to `render()` with calls to `reactRender()`
- replace the `areaName` property with `name`
- continue with #27 :+1:

Before:
```js
function create( reactRender ) {
   function render() {
      reactRender(<em>Yo</em>);
   };

   setTimeout(render, 2000);

   return {
      onDomAvailable: () => render()
   };
};
```

After:
```js
function create( reactRender ) {
   function render() {
      return <em>Yo</em>;
   };

   setTimeout(reactRender, 2000);

   return render;
};
```
